LiquorStoreFinalProject/Areas/Admin/ViewModels/Blog/CreateBlogVM.cs
namespace LiquorStoreFinalProject.Areas.Admin.ViewModels.Blog
{
    public class CreateBlogVM
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public IFormFile Image { get; set; }
    }
}

LiquorStoreFinalProject/Areas/Admin/ViewModels/Blog/UpdateBlogVM.cs
namespace LiquorStoreFinalProject.Areas.Admin.ViewModels.Blog
{
    public class UpdateBlogVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string? ImageURL { get; set; }
        public IFormFile Image { get; set; }
    }
}

LiquorStoreFinalProject/Models/Blog.cs
namespace LiquorStoreFinalProject.Models
{
    public class Blog:BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
    }
}

LiquorStoreFinalProject/Areas/Admin/Controllers/BlogController.cs
using LiquorStoreFinalProject.Areas.Admin.ViewModels.Blog;
using LiquorStoreFinalProject.Helpers;
using LiquorStoreFinalProject.Models;
using LiquorStoreFinalProject.Services;
using LiquorStoreFinalProject.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LiquorStoreFinalProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;

        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            var blogs = await _blogService.GetPaginatedDatasAsync(page);
            return View(blogs);
        }
        [HttpGet]
        public async Task<IActionResult> CreateBlog()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBlog(CreateBlogVM request)
        {
            await _blogService.CreateAsync(request);
            return RedirectToAction(nameof(Index));
        }

        //Update
        [HttpGet]
        public async Task<IActionResult> UpdateBlog(int id)
        {
            Blog blog = _blogService.GetBlogById(id);
            UpdateBlogVM updateBlogVM = new UpdateBlogVM()
            {
                Id=blog.Id,
                Description=blog.Description,
                ImageURL=blog.ImageURL,
                Title=blog.Title,
            };
            return View(updateBlogVM);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBlog(UpdateBlogVM request)
        {
            await _blogService.UpdateAsync(request);
            return NoContent();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteBlog(int id)
        {
            await _blogService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

LiquorStoreFinalProject/Controllers/BlogsController.cs
using LiquorStoreFinalProject.Data;
using LiquorStoreFinalProject.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LiquorStoreFinalProject.Controllers
{
    public class BlogsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IBlogService _blogService;
        public BlogsController(AppDbContext context, IBlogService blogService)
        {
            _context = context;
            _blogService = blogService;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            var blogs = await _blogService.GetPaginatedDatasAsync(page);
            return View(blogs);
        }
        public async Task<IActionResult> BlogDetails(int id)
        {
            ViewBag.Recent3Blogs = _context.Blogs.Take(3).OrderByDescending(b => b.CreatedDate).ToList();
            var blog =  _context.Blogs.FirstOrDefault(b => b.Id == id);
            return View(blog);
        }

    }
}

LiquorStoreFinalProject/Views/Blogs/Index.cshtml
@using LiquorStoreFinalProject.ViewModels;
@model GetPaginatedBlogVM
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Liquor Store - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;0,400;0,500;0,700;0,800;1,200;1,300;1,400;1,500;1,700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../../stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="~/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="~/assets/css/flaticon.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <script nonce="8075eba7-d93f-4b45-a44a-a5b39a95c4d2">(function (w, d) { !function (bt, bu, bv, bw) { bt[bv] = bt[bv] || {}; bt[bv].executed = []; bt.zaraz = { deferred: [], listeners: [] }; bt.zaraz.q = []; bt.zaraz._f = function (bx) { return function () { var by = Array.prototype.slice.call(arguments); bt.zaraz.q.push({ m: bx, a: by }) } }; for (const bz of ["track", "set", "debug"]) bt.zaraz[bz] = bt.zaraz._f(bz); bt.zaraz.init = () => { var bA = bu.getElementsByTagName(bw)[0], bB = bu.createElement(bw), bC = bu.getElementsByTagName("title")[0]; bC && (bt[bv].t = bu.getElementsByTagName("title")[0].text); bt[bv].x = Math.random(); bt[bv].w = bt.screen.width; bt[bv].h = bt.screen.height; bt[bv].j = bt.innerHeight; bt[bv].e = bt.innerWidth; bt[bv].l = bt.location.href; bt[bv].r = bu.referrer; bt[bv].k = bt.screen.colorDepth; bt[bv].n = bu.characterSet; bt[bv].o = (new Date).getTimezoneOffset(); if (bt.dataLayer) for (const bG of Object.entries(Object.entries(dataLayer).reduce(((bH, bI) => ({ ...bH[1], ...bI[1] })), {}))) zaraz.set(bG[0], bG[1], { scope: "page" }); bt[bv].q = []; for (; bt.zaraz.q.length;) { const bJ = bt.zaraz.q.shift(); bt[bv].q.push(bJ) } bB.defer = !0; for (const bK of [localStorage, sessionStorage]) Object.keys(bK || {}).filter((bM => bM.startsWith("_zaraz_"))).forEach((bL => { try { bt[bv]["z_" + bL.slice(7)] = JSON.parse(bK.getItem(bL)) } catch { bt[bv]["z_" + bL.slice(7)] = bK.getItem(bL) } })); bB.referrerPolicy = "origin"; bB.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(bt[bv]))); bA.parentNode.insertBefore(bB, bA) };["complete", "interactive"].includes(bu.readyState) ? zaraz.init() : bt.addEventListener("DOMContentLoaded", zaraz.init) }(w, d, "zarazData", "script"); })(window, document);</script>
</head>
<body>

    <section class="hero-wrap hero-wrap-2" style="background-image: url('@Url.Content("~/assets/images/bg_2.jpg")');" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate mb-5 text-center">
                    <p class="breadcrumbs mb-0"><span class="mr-2"><a href="index.html">Home <i class="fa fa-chevron-right"></i></a></span> <span>Blog <i class="fa fa-chevron-right"></i></span></p>
                    <h2 class="mb-0 bread">Blog</h2>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section">
        <div class="container">
            <div class="row d-flex">
                @foreach (var blog in Model.Blogs)
                {
                    <div class="col-lg-6 d-flex align-items-stretch ftco-animate">
                        <div class="blog-entry d-md-flex">
                            <a href="blog-single.html" class="block-20 img" style="background-image: url('@Url.Content($"~/{blog.ImageURL}")');">
                            </a>
                            <div class="text p-4 bg-light">
                                <div class="meta">
                                    <p><span class="fa fa-calendar"></span>@blog.CreateDate.ToString("dd MMMM yyyy")</p>
                                </div>
                                <h3 class="heading mb-3"><a href="@Url.Action("BlogDetails", "Blogs", new { id = blog.Id })">@blog.Title</a></h3>
                                <p>@blog.Description</p>
                                <a href="@Url.Action("BlogDetails", "Blogs", new { id = blog.Id })" class="btn-custom">Continue <span class="fa fa-long-arrow-right"></span></a>
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="row mt-5">
                <div class="col text-center">
                    <div class="block-27">
                        <ul>
                            @for (int i = 1; i <= Model.Pages; i++)
                            {
                                <li><a href="@Url.Action("Index", new { page = i })">@i</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/jquery.easing.1.3.js"></script>
    <script src="~/assets/js/jquery.waypoints.min.js"></script>
    <script src="~/assets/js/jquery.stellar.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.min.js"></script>
    <script src="~/assets/js/jquery.animateNumber.min.js"></script>
    <script src="~/assets/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
    <script src="~/assets/js/google-map.js"></script>
    <script src="~/assets/js/main.js"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"7ee5fa0c59153a5a","version":"2023.7.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}' crossorigin="anonymous"></script>
</body>
</html>